linters:
  disable-all: true
  enable:
    - gci
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - exhaustive

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/MerlinKodo/clash-rev)
      - default
  staticcheck:
    go: '1.21'
  exhaustive:
    default-signifies-exhaustive: true
